### ISSUE TITLE
accept federated share on marie side cause some weird errors

### ISSUE THREAD

**Issue by navid-shokri** [SURFnet/rd-sram-integration#114]
the shared file is accepted but it is not listed in receiver side (marie). and this Error is shown in side the log:

```
{"reqId":"wRsdZlhCjn5jgBMQToJ9","level":3,"time":"2023-02-28T16:50:09+00:00","remoteAddr":"172.18.0.6","user":"marie","app":"no app in context","method":"PROPFIND","url":"\/remote.php\/dav\/files\/marie\/","message":"Exception: {\"Exception\":\"Sabre\\\\HTTP\\\\ClientHttpException\",\"Message\":\"Unauthorized\",\"Code\":401,\"Trace\":\"
#0 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Client.php(229): Sabre\\\\HTTP\\\\Client->send()\\n
#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(264): Sabre\\\\DAV\\\\Client->propFind()\\n
#2 \\\/var\\\/www\\\/html\\\/apps\\\/rd-sram-integration\\\/federatedgroups\\\/lib\\\/Files_Sharing\\\/External\\\/Storage.php(327): OC\\\\Files\\\\Storage\\\\DAV->propfind()\\n
#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(637): OCA\\\\FederatedGroups\\\\Files_Sharing\\\\External\\\\Storage->getPermissions()\\n
#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Common->getMetaData()\\n
#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(459): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n
#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(177): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->getMetaData()\\n
#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Checksum.php(206): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getMetaData()\\n
#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum->getMetaData()\\n
#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(115): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n
#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(150): OC\\\\Files\\\\Cache\\\\Scanner->getData()\\n
#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/View.php(1569): OC\\\\Files\\\\Cache\\\\Scanner->scanFile()\\n
#12 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(295): OC\\\\Files\\\\View->getDirectoryContent()\\n
#13 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/SharesPlugin.php(171): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChildren()\\n
#14 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->handleGetProperties()\\n
#15 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1052): Sabre\\\\DAV\\\\Server->emit()\\n
#16 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(984): Sabre\\\\DAV\\\\Server->getPropertiesByNode()\\n
#17 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1662): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath()\\n
#18 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1642): Sabre\\\\DAV\\\\Server->writeMultiStatus()\\n
#19 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Sapi.php(83): Sabre\\\\DAV\\\\Server->Sabre\\\\DAV\\\\{closure}(*** sensitive parameters replaced ***)\\n
#20 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(490): Sabre\\\\HTTP\\\\Sapi::sendResponse()\\n
#21 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n
#22 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(348): Sabre\\\\DAV\\\\Server->start()\\n
#23 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n
#24 \\\/var\\\/www\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n
#25 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Client.php\",\"Line\":163}"}

```

_Originally posted by @navid-shokri in https://github.com/SURFnet/rd-sram-integration/issues/93#issuecomment-1448525760_

**Comment by navid-shokri** [comment]
this error is shown in `oc1` /var/log/apache2/access.log

> 172.18.0.5 - - [03/Mar/2023:09:44:54 +0000] "GET /ocm-provider/ HTTP/1.1" 200 3233 "-" "ownCloud Server Crawler"
172.18.0.5 - xaz0UM46oyf79I6 [03/Mar/2023:09:44:54 +0000] "PROPFIND /public.php/webdav/ HTTP/1.1" 401 3328 "-" "sabre-dav/4.4.0 (http://sabre.io/)"

and this one is shown in `oc1` data/owncloud.log

> {"reqId":"wDdSOIrd3IXXhcRu9ZBC","level":3,"time":"2023-03-03T09:52:56+00:00","remoteAddr":"172.18.0.5","user":"--","app":"no app in context","method":"PROPFIND","url":"\/public.php\/webdav\/","message":"PublicAuth: share for found xaz0UM46oyf79I6"}

**Comment by navid-shokri** [comment]
I tested the user-to-user federated share ( Einstein -> Marie ) and it works properly :information_source: 
so we can be sure that the problem is related to group sharing (Einstein -> helpdesk);

**Comment by navid-shokri** [comment]
It is the data in database after accepting the shared file: 

MariaDB [owncloud]> select * from oc_share_external_group; 

MariaDB [owncloud]> select * from oc_share_external_group; 


| id | parent | share_type | remote             | remote_id | share_token     | password | name  | owner    | user     | mountpoint                        | mountpoint_hash                  | accepted | lastscan   |
|----|--------|------------|--------------------|-----------|-----------------|----------|-------|----------|----------|-----------------------------------|----------------------------------|----------|------------|
|  1 |   NULL |          7 | https://oc1.docker | 1         | xaz0UM46oyf79I6 |          | /init | einstein | helpdesk | {{TemporaryMountPointName#/init}} | 5e44cb4cd363dc82b03c1b2d7965bacf |        0 | 1677835696 |
|  2 |      1 |          6 | https://oc1.docker | 1         | xaz0UM46oyf79I6 |          | /init | einstein | marie    | {{TemporaryMountPointName#/init}} | 5e44cb4cd363dc82b03c1b2d7965bacf |        0 | 1677835696 |

**Comment by navid-shokri** [comment]
after following the execution I found that the problem is raised from this function: :information_source: 

https://github.com/SURFnet/rd-sram-integration/blob/19bca6a95a19056734867bbec799895aa94b51f6/federatedgroups/lib/Files_Sharing/External/Manager.php#L217

**Comment by navid-shokri** [comment]
oh, finally I found it. :tada: 
https://github.com/pondersource/core/blob/e5e3da4ee8179055d479025404f7b70996d5fed3/apps/dav/lib/Connector/PublicAuth.php#L85

this Connector is Called after the acceptance attempt by Marie inside the Einstein  Server **AND** the __getShareByToken__ function cannot find the shared item by the given token. :confused:

**Comment by navid-shokri** [comment]
finally finished :tada: :checkered_flag: 

the issue was finally resolved there were two problems: 
1- the getShareByToken was not overridden in https://github.com/SURFnet/rd-sram-integration/blob/6e5caf21999bd69b776513cd4bb537c54c2d1cbe/federatedgroups/lib/FederatedGroupShareProvider.php#L552

2- some changes that I made in core by this commit:
https://github.com/pondersource/core/commit/b77c7da7a8b9e0026287a158a6ec51fe2e9ad041
