### ISSUE TITLE
not seeing share added in oc_share_external_group

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#126]
In the demo for milestone 3, at some point almere.pondersource.net makes an OCM call to federalists@castricum.pondersource.net.
This call seems to be successful.
But afterwards, I can't see the share in oc_share_external_group.
Needs some more debugging

**Comment by michielbdejong** [comment]
When adding a new share to a group, it works:
```
[Tue Mar 28 08:42:11.994983 2023] [php7:notice] [pid 13] [client 45.32.236.27:51522] FederatedGroups ProviderFactory constructor
[Tue Mar 28 08:42:12.006070 2023] [php7:notice] [pid 13] [client 45.32.236.27:51522] in core OcmController group yes
[Tue Mar 28 08:42:12.006114 2023] [php7:notice] [pid 13] [client 45.32.236.27:51522] in core OcmController yes
[Tue Mar 28 08:42:12.007716 2023] [php7:notice] [pid 13] [client 45.32.236.27:51522] Federated Groups OcmController constructed
[Tue Mar 28 08:42:12.007734 2023] [php7:notice] [pid 13] [client 45.32.236.27:51522] Federated Groups OcmController creating share
[Tue Mar 28 08:42:12.008505 2023] [php7:notice] [pid 13] [client 45.32.236.27:51522] checking if group federalists exists
[Tue Mar 28 08:42:12.009120 2023] [php7:notice] [pid 13] [client 45.32.236.27:51522] Calling our FedShareManager for type group
[Tue Mar 28 08:42:12.009139 2023] [php7:notice] [pid 13] [client 45.32.236.27:51522] Our FedShareManager creating share of type group
```
When adding a new user to a group, it does not work:
```
Tue Mar 28 08:39:37.010783 2023] [php7:notice] [pid 24] [client 138.68.152.182:43910] sendRemoteShare
[Tue Mar 28 08:39:37.010810 2023] [php7:notice] [pid 24] [client 138.68.152.182:43910] sendOcmRemoteShare group
[Tue Mar 28 08:39:37.010879 2023] [php7:notice] [pid 24] [client 138.68.152.182:43910] Calling try...
[Tue Mar 28 08:39:37.010886 2023] [php7:notice] [pid 24] [client 138.68.152.182:43910] tryHttpPostToShareEndpoint bergambacht.pondersource.net /shares
[Tue Mar 28 08:39:37.063018 2023] [php7:notice] [pid 24] [client 138.68.152.182:43910] posting to https://bergambacht.pondersource.net/index.php/apps/federatedfilesharing/shares
{"reqId":"H1dDyh1KgUOEUrIayzfQ","level":3,"time":"2023-03-28T08:39:37+00:00","remoteAddr":"138.68.152.182","user":"--","app":"no app in context","method":"POST","url":"\/index.php\/apps\/federatedgroups\/scim\/Groups","message":"Failed to notify remote server of mixed group share, panic (Sharing for-federalists failed, could not find federalists, maybe the server is currently unreachable.)"}
{"reqId":"H1dDyh1KgUOEUrIayzfQ","level":3,"time":"2023-03-28T08:39:37+00:00","remoteAddr":"138.68.152.182","user":"--","app":"index","method":"POST","url":"\/index.php\/apps\/federatedgroups\/scim\/Groups","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Sharing for-federalists failed, could not find federalists, maybe the server is currently unreachable.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/apps\\\/rd-sram-integration\\\/federatedgroups\\\/lib\\\/MixedGroupShareProvider.php(352): OCA\\\\FederatedGroups\\\\MixedGroupShareProvider->sendOcmInvite()\\n#1 \\\/var\\\/www\\\/html\\\/apps\\\/rd-sram-integration\\\/federatedgroups\\\/lib\\\/Controller\\\/ScimController.php(165): OCA\\\\FederatedGroups\\\\MixedGroupShareProvider->newDomainInGroup()\\n#2 \\\/var\\\/www\\\/html\\\/apps\\\/rd-sram-integration\\\/federatedgroups\\\/lib\\\/Controller\\\/ScimController.php(188): OCA\\\\FederatedGroups\\\\Controller\\\\ScimController->doUpdateGroup()\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OCA\\\\FederatedGroups\\\\Controller\\\\ScimController->createGroup()\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match()\\n#9 \\\/var\\\/www\\\/html\\\/index.php(54): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/rd-sram-integration\\\/federatedgroups\\\/lib\\\/MixedGroupShareProvider.php\",\"Line\":194}"}
