### ISSUE TITLE
Error message in logs (but share arrives)

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#244]
```
{"reqId":"ZQReDrGFmGS3ScN_j-vqewAAAA4","level":3,"time":"15\/Sep\/2023:15:37:20","remoteAddr":"10.234.2.172","user":"afad2da3-2815-466d-8fd0-74b1573e0687@eduid.nl","app":"no app in context",
"method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/remote_shares\/all?format=json&include_tags=true",
"message":"Exception: {\"Exception\":\"Sabre\\\\HTTP\\\\ClientHttpException\",\"Message\":\"Unauthorized\",\"Code\":401,
\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Client.php(229): Sabre\\\\HTTP\\\\Client->send()\\n
#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(264): Sabre\\\\DAV\\\\Client->propFind()\\n
#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Storage.php(378): OC\\\\Files\\\\Storage\\\\DAV->propfind()\\n
#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(637): OCA\\\\Files_Sharing\\\\External\\\\Storage->getPermissions()\\n
#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Common->getMetaData()\\n
#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(459): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n
#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Checksum.php(206): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->getMetaData()\\n
#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum->getMetaData()\\n
#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n
#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(115): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n
#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(150): OC\\\\Files\\\\Cache\\\\Scanner->getData()\\n
#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(326): OC\\\\Files\\\\Cache\\\\Scanner->scanFile()\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1409): OC\\\\Files\\\\Cache\\\\Scanner->scan()\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1452): OC\\\\Files\\\\View->getCacheEntry()\\n#14 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/RemoteOcsController.php(307): OC\\\\Files\\\\View->getFileInfo()\\n#15 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/RemoteOcsController.php(289): OCA\\\\Files_Sharing\\\\Controller\\\\RemoteOcsController->getFileInfo()\\n#16 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/RemoteOcsController.php(196): OCA\\\\Files_Sharing\\\\Controller\\\\RemoteOcsController->extendShareInfo()\\n#17 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/RemoteOcsController.php(239): OCA\\\\Files_Sharing\\\\Controller\\\\RemoteOcsController->getShares()\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OCA\\\\Files_Sharing\\\\Controller\\\\RemoteOcsController->getAllShares()\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#21 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#22 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#23 \\\/var\\\/www\\\/owncloud\\\/ocs\\\/v1.php(84): OC\\\\Route\\\\Router->match()\\n#24 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Client.php\",\"Line\":163}"}

{"reqId":"ZQReDrGFmGS3ScN_j-vqewAAAA4","level":3,"time":"15\/Sep\/2023:15:37:20","remoteAddr":"10.234.2.172","user":"afad2da3-2815-466d-8fd0-74b1573e0687@eduid.nl","app":"files_external",
"method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/remote_shares\/all?format=json&include_tags=true","message":"Unauthorized"}
{"reqId":"ZQReDrGFmGS3ScN_j-vqewAAAA4","level":3,"time":"15\/Sep\/2023:15:37:20","remoteAddr":"10.234.2.172",
"user":"afad2da3-2815-466d-8fd0-74b1573e0687@eduid.nl","
app":"files_sharing","
method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/remote_shares\/all?format=json&include_tags=true",
"message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageInvalidException\",\"Message\":\"Sabre\\\\HTTP\\\\ClientHttpException: Unauthorized\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(860): OC\\\\Files\\\\Storage\\\\DAV->throwByStatusCode()\\n
#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(279): OC\\\\Files\\\\Storage\\\\DAV->convertException()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Storage.php(378): OC\\\\Files\\\\Storage\\\\DAV->propfind()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(637): OCA\\\\Files_Sharing\\\\External\\\\Storage->getPermissions()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Common->getMetaData()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(459): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Checksum.php(206): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->getMetaData()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum->getMetaData()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(586): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(115): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getMetaData()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(150): OC\\\\Files\\\\Cache\\\\Scanner->getData()\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(326): OC\\\\Files\\\\Cache\\\\Scanner->scanFile()\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1409): OC\\\\Files\\\\Cache\\\\Scanner->scan()\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1452): OC\\\\Files\\\\View->getCacheEntry()\\n#14 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/RemoteOcsController.php(307): OC\\\\Files\\\\View->getFileInfo()\\n#15 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/RemoteOcsController.php(289): OCA\\\\Files_Sharing\\\\Controller\\\\RemoteOcsController->getFileInfo()\\n#16 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/RemoteOcsController.php(196): OCA\\\\Files_Sharing\\\\Controller\\\\RemoteOcsController->extendShareInfo()\\n#17 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/RemoteOcsController.php(239): OCA\\\\Files_Sharing\\\\Controller\\\\RemoteOcsController->getShares()\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OCA\\\\Files_Sharing\\\\Controller\\\\RemoteOcsController->getAllShares()\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#21 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#22 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#23 \\\/var\\\/www\\\/owncloud\\\/ocs\\\/v1.php(84): OC\\\\Route\\\\Router->match()\\n#24 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php\",\"Line\":896}"}
{"reqId":"ZQReDrGFmGS3ScN_j-vqewAAAA4","level":1,"time":"15\/Sep\/2023:15:37:20","remoteAddr":"10.234.2.172","user":"afad2da3-2815-466d-8fd0-74b1573e0687@eduid.nl","app":"core","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/remote_shares\/all?format=json&include_tags=true","message":"cleaning 1 stray shared locks for files\/c6f2a5ec5d25770ae65146b51dd091a1"}

**Comment by michielbdejong** [comment]
This bug magically disappeared after a re-deploy :)
