### ISSUE TITLE
ExternalManager not found

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#71]
[Mon Jan 30 09:34:37.793855 2023] [php7:notice] [pid 165] [client 172.18.0.6:52060] fg: OCP\\AppFramework\\App
[Mon Jan 30 09:34:37.805550 2023] [php7:notice] [pid 165] [client 172.18.0.6:52060] FederatedGroups ProviderFactory constructor
{"reqId":"XxDaQQcxTI1RejKITgns","level":3,"time":"2023-01-30T09:34:37+00:00","remoteAddr":"172.18.0.6","user":"marie","app":"index","method":"GET","url":"\/index.php\/apps\/files\/?dir=\/&","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve ExternalManager! Class ExternalManager does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(109): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve()\\n#1 \\\/var\\\/www\\\/html\\\/apps\\\/rd-sram-integration\\\/federatedgroups\\\/lib\\\/AppInfo\\\/Application.php(52): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query()\\n#2 \\\/var\\\/www\\\/html\\\/apps\\\/rd-sram-integration\\\/federatedgroups\\\/lib\\\/FilesSharing\\\/External\\\/MountProvider.php(53): OCA\\\\FederatedGroups\\\\AppInfo\\\\Application->OCA\\\\FederatedGroups\\\\AppInfo\\\\{closure}(*** sensitive parameters replaced ***)\\n#3 \\\/var\\\/www\\\/html\\\/apps\\\/rd-sram-integration\\\/federatedgroups\\\/lib\\\/FilesSharing\\\/External\\\/MountProvider.php(78): OCA\\\\FederatedGroups\\\\FilesSharing\\\\External\\\\MountProvider->getMount()\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(82): OCA\\\\FederatedGroups\\\\FilesSharing\\\\External\\\\MountProvider->getMountsForUser()\\n#5 [internal function]: OC\\\\Files\\\\Config\\\\MountProviderCollection->OC\\\\Files\\\\Config\\\\{closure}(*** sensitive parameters replaced ***)\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(83): array_map()\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Filesystem.php(445): OC\\\\Files\\\\Config\\\\MountProviderCollection->getMountsForUser()\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Filesystem.php(372): OC\\\\Files\\\\Filesystem::initMountPoints()\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/util.php(314): OC\\\\Files\\\\Filesystem::init()\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(912): OC_Util::setupFS()\\n#11 \\\/var\\\/www\\\/html\\\/index.php(54): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":95}"}

**Comment by michielbdejong** [comment]
@navid-dada to reproduce this, make sure you are on the main branch of this repo,
Inside oc1/2.docker /var/www/html you may have to do a `git pull` to get the latest surf-dev branch of the core repo into the containers.
Then comment out [this line](https://github.com/SURFnet/rd-sram-integration/commit/f991ce7709aa5ddaa593cb9dea1d9e1abc8ff161#diff-abb9178683b2414e0a945243f2ccec6715fda77d50490c2277ab6b55390db7c4R61) as discussed
Then to reproduce:
* Einstein creates a folder 'asdf' and shares it with marie@oc2.docker
* Einstein creates a folder 'qwer' and shares it with helpdesk@oc2.docker
* Marie visits https://oc2.docker/index.php/apps/files/?dir=/&fileid=3
* This triggers this 500 error in the oc2.docker logs

**Comment by michielbdejong** [comment]
@navid-dada you mentioned in the meeting that the error was that you hadn't registered a manager, and that you're creating a PR for this now.

**Comment by michielbdejong** [comment]
And that would also fix issue #73

**Comment by michielbdejong** [comment]
This was fixed
